In [7]:
import pandas as pd

In [8]:
df = pd.read_csv('nasdaq_screener_1701174290288.csv')
df.head()

,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,Sector,Industry
0,A,Agilent Technologies Inc. Common Stock,$125.01,-1.6100,-1.272%,3.657633e+10,United States,1999.0,2255398,Industrials,Electrical Products
1,AA,Alcoa Corporation Common Stock,$26.30,0.0600,0.229%,4.693811e+09,United States,2016.0,3428999,Industrials,Aluminum
2,AACG,ATA Creativity Global American Depositary Shares,$0.85,-0.0749,-8.098%,2.687884e+07,China,2008.0,3742,Real Estate,Other Consumer Services
3,AACI,Armada Acquisition Corp. I Common Stock,$10.77,0.0000,0.00%,0.000000e+00,United States,2021.0,47,Finance,Blank Checks
4,AACIU,Armada Acquisition Corp. I Unit,$10.81,0.0000,0.00%,0.000000e+00,United States,2021.0,6,Finance,Blank Checks

In [9]:
df =df.nlargest(500,['Market Cap'])
df.to_csv('top500marketcap.csv',index=False)

In [10]:
df

,Symbol,Name,Last Sale,Net Change,% Change,Market Cap,Country,IPO Year,Volume,Sector,Industry
19,AAPL,Apple Inc. Common Stock,$189.79,-0.18,-0.095%,2.951757e+12,United States,1980.0,40552609,Technology,Computer Manufacturing
4400,MSFT,Microsoft Corporation Common Stock,$378.61,1.18,0.313%,2.813929e+12,United States,1986.0,22179228,Technology,Computer Software: Prepackaged Software
2964,GOOG,Alphabet Inc. Class C Capital Stock,$138.05,-0.17,-0.123%,1.727834e+12,United States,2004.0,17886389,Technology,Computer Software: Programming Data Processing
2965,GOOGL,Alphabet Inc. Class A Common Stock,$136.41,-0.28,-0.205%,1.707308e+12,United States,2004.0,23436526,Technology,Computer Software: Programming Data Processing
408,AMZN,Amazon.com Inc. Common Stock,$147.73,0.99,0.675%,1.526646e+12,United States,1997.0,53762428,Consumer Discretionary,Catalog/Specialty Distribution
...,...,...,...,...,...,...,...,...,...,...,...
6265,STE,STERIS plc (Ireland) Ordinary Shares,$201.40,-1.79,-0.881%,1.989835e+10,United States,NaN,415606,Health Care,Industrial Specialties
4411,MT,Arcelor Mittal NY Registry Shares NEW,$24.63,0.27,1.108%,1.983547e+10,Luxembourg,NaN,1619089,Industrials,Steel/Iron Ore
4065,LYV,Live Nation Entertainment Inc. Common Stock,$85.96,-1.67,-1.906%,1.979877e+10,United States,NaN,1715046,Consumer Discretionary,Services-Misc. Amusement & Recreation
1774,CTRA,Coterra Energy Inc. Common Stock,$26.27,-0.50,-1.868%,1.976008e+10,United States,NaN,4951459,Energy,Oil & Gas Production
1282,CCJ,Cameco Corporation Common Stock,$45.43,0.30,0.665%,1.971051e+10,Canada,1996.0,4082494,Basic Materials,Other Metals and Minerals